# Generated by Django 2.1.2 on 2018-11-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=200, verbose_name='硬盘信息'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='ids',
            field=models.CharField(max_length=200, unique=True, verbose_name='机房标识'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='机房名称'),
        ),
    ]
