# Generated by Django 2.1.2 on 2018-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181104_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(blank=True, max_length=100, verbose_name='硬盘信息'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memo',
            field=models.TextField(blank=True, max_length=100, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='ids',
            field=models.CharField(max_length=100, unique=True, verbose_name='机房标识'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='memo',
            field=models.TextField(blank=True, max_length=100, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='机房名称'),
        ),
    ]
